package core

var drivers []string = []string{ // Sandbox drivers taken from https://github.com/LordNoteworthy/al-khaser
  "C:\\Windows\\System32\\drivers\\VBoxMouse.sys",
  "C:\\Windows\\System32\\drivers\\VBoxGuest.sys",
  "C:\\Windows\\System32\\drivers\\VBoxSF.sys",
  "C:\\Windows\\System32\\drivers\\VBoxVideo.sys",
  "C:\\Windows\\System32\\vboxdisp.dll",
  "C:\\Windows\\System32\\vboxhook.dll",
  "C:\\Windows\\System32\\vboxmrxnp.dll",
  "C:\\Windows\\System32\\vboxogl.dll",
  "C:\\Windows\\System32\\vboxoglarrayspu.dll",
  "C:\\Windows\\System32\\vboxservice.exe",
  "C:\\Windows\\System32\\vboxtray.exe",
  "C:\\Windows\\System32\\VBoxControl.exe",
  "C:\\Windows\\System32\\drivers\\vmmouse.sys",
  "C:\\Windows\\System32\\drivers\\vmhgfs.sys",
  "C:\\Windows\\System32\\drivers\\vmci.sys",
  "C:\\Windows\\System32\\drivers\\vmmemctl.sys",
  "C:\\Windows\\System32\\drivers\\vmmouse.sys",
  "C:\\Windows\\System32\\drivers\\vmrawdsk.sys",
  "C:\\Windows\\System32\\drivers\\vmusbmouse.sys",
}

var processes []string = []string{ // Sandbox processes taken from https://github.com/LordNoteworthy/al-khaser
  "vboxservice.exe",
  "vboxtray.exe",
  "vmtoolsd.exe",
  "vmwaretray.exe",
  "vmware.exe",
  "vmware-vmx.exe",
  "vmwareuser",
  "VGAuthService.exe",
  "vmacthlp.exe",
  "vmsrvc.exe",
  "vmusrvc.exe",
  "xenservice.exe",
  "qemu-ga.exe",
  // Some extra processes (added by me)
  "wireshark.exe",
  "Procmon.exe",
  "Procmon64.exe",
  "volatily.exe",
  "volatily3.exe",
  "DumpIt.exe",
  "dumpit.exe",
}

var hostnames_list []string = []string{
  "Sandbox",
  "SANDBOX",
  "malware",
  "virus",
  "Virus",
  "sample",
  "debug",
  "USER-PC",
  "analysis",
  "cuckoo",
  "cuckoofork",
  "Cuckoo",
}

var usernames_list []string = []string{
  "sandbox",
  "virus",
  "malware",
  "debug4fun",
  "debug",
  "sys",
  "user1",
  "Virtual",
  "virtual",
  "analyis",
  "trans_iso_0",
  "j.yoroi",
  "venuseye",
  "VenusEye",
  "VirusTotal",
  "virustotal",
}

